### ISSUE TITLE
Add temporal autocorrelation

### ISSUE THREAD

**Issue by jo-mueller** [campaslab/napari-stress#192]
Final feature that is currently missing here. @GrossBJ - is there a specific reason why the radial manifold formulation is used in the original code rather than the formulation in cartesian coordinates?

**Comment by jo-mueller** [comment]
Nvm, I think I get it: Temporal autocorrelations are first calculated for every point on the surface (as determined by latitude/longitutde on the radial manifold) and then averaged across all points?

**Comment by jo-mueller** [comment]
Another follow-up question:

In the original code ([Link](https://github.com/campaslab/STRESS/blob/29c6627cb4c95330567cde5d0189238e3b95d7ab/Batch_Droplet_Class_Analysis.py#L403) the stresses on the radial manifold are calculated as follows:

```Python
Anis_Stress_Rad_pts.append(Drop_i.Anis_Stress_pts_Rad_lbdv.flatten())
Cell_Stress_Rad_pts.append(Drop_i.Anis_Cell_Stress_pts_lbdv.flatten())
Tissue_Stress_Rad_pts.append(Drop_i.Anis_Tissue_Stress_pts_lbdv.flatten())
```

whereas the first (`Anis_Stress_pts_Rad_lbdv`) is the total stress calculated on the radial manifold and the other two (`Anis_Cell_Stress_pts_lbdv` and `Anis_Tissue_Stress_pts_lbdv`) are calculated on the cartesian manifold. The three are then used to calculate temporal autocorrelations.

In the paper it is claimed that the radial manifold is used to calculate all temporal autocorrelations whereas that doesn't seem to be the case here. Is there something I'm missing? 🤔 

Sorry to bother you again on this one @GrossBJ

**Comment by GrossBJ** [comment]
Hi Johannes,
No worries I'm always happy to hear from you!
 I've been reviewing the code and it may be a typo. I did find the field self.Anis_Stress_pts_Rad_lbdv in the code which might also be able to be used here for this calculation. Are you implementing a version of this yourself?
For purely spatial correlations the elliptical coordinate system works, but for temporal correlations radial coordinates are needed for consistency between droplet shapes.
-Ben

Enviado desde Yahoo Mail para Android 
 
  El jue, 3 de nov. de 2022 a la(s) 15:00, Johannes ***@***.***> escribió:   


Another follow-up question:

In the original code (Link the stresses on the radial manifold are calculated as follows:
Anis_Stress_Rad_pts.append(Drop_i.Anis_Stress_pts_Rad_lbdv.flatten())
Cell_Stress_Rad_pts.append(Drop_i.Anis_Cell_Stress_pts_lbdv.flatten())
Tissue_Stress_Rad_pts.append(Drop_i.Anis_Tissue_Stress_pts_lbdv.flatten())
whereas the first (Anis_Stress_pts_Rad_lbdv) is the total stress calculated on the radial manifold and the other two (Anis_Cell_Stress_pts_lbdv and Anis_Tissue_Stress_pts_lbdv) are calculated on the cartesian manifold. The three are then used to calculate temporal autocorrelations.

In the paper it is claimed that the radial manifold is used to calculate all temporal autocorrelations whereas that doesn't seem to be the case here. Is there something I'm missing? 🤔
 
Sorry to bother you again on this one @GrossBJ

**Comment by jo-mueller** [comment]
Hi @GrossBJ ,

> No worries I'm always happy to hear from you!

Thanks!

>  Are you implementing a version of this yourself?

Nah, I'm just copy-pasting code from the stress repository to separate functions here so that the whole becomes a bit easier to maintain. I'm not trying to reinvent the wheel :)

As for the radial manifold, I think it's alright for the total stress as you write but I'm not sure for the tissue stresses and the cell-scale stresses. The stresses on the radial manifold are calculated [here](https://github.com/campaslab/STRESS/blob/29c6627cb4c95330567cde5d0189238e3b95d7ab/Refactored_Droplet_Class.py#L1109) (copying more code here to get the context):

```python
# Use Gauss-Bonnet to test our resolution of the Radial manifold:
Rad_K_lbdv_pts = euc_kf.Combine_Chart_Quad_Vals(Manny_Rad.K_A_pts, Manny_Rad.K_B_pts, LBDV_VOL)
Gauss_Bonnet_Err_Rad = euc_kf.Integral_on_Manny(Rad_K_lbdv_pts, Manny_Rad, LBDV_VOL) - 4*np.pi
self.Gauss_Bonnet_Rel_Err_Rad = abs(Gauss_Bonnet_Err_Rad)/(4*np.pi)

Mean_Curv_Rad_lbdv_pts_unsigned = euc_kf.Combine_Chart_Quad_Vals(Manny_Rad.H_A_pts, Manny_Rad.H_B_pts, LBDV_VOL)

We estimate H0 on Radial Manifold: Integratal of H_Rad (on surface) divided by Rad surface area:
Ones_pts = 1.*(np.ones_like(Mean_Curv_Rad_lbdv_pts_unsigned))
H0_Rad_Int_of_H_over_Area = euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts_unsigned, Manny_Rad, LBDV_VOL) / euc_kf.Integral_on_Manny(Ones_pts, Manny_Rad, LBDV_VOL)

abs_H0_Rad_Int_of_H_over_Area = abs(H0_Rad_Int_of_H_over_Area) # should be positive
Mean_Curv_Rad_lbdv_pts = Mean_Curv_Rad_lbdv_pts_unsigned*abs_H0_Rad_Int_of_H_over_Area/H0_Rad_Int_of_H_over_Area # flip sign, if needed		
self.Anis_Stress_pts_Rad_lbdv = self.TwoGammaVal*(Mean_Curv_Rad_lbdv_pts - abs_H0_Rad_Int_of_H_over_Area)
		
Error in H approx between manifolds:
self.Mean_Curv_diff_Mannys = 0.5*( euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts - self.Mean_Curv_lbdv_pts, Manny_Rad, LBDV_VOL) + euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts - self.Mean_Curv_lbdv_pts, Manny, LBDV_Fit) )
```

where `self.Anis_Stress_pts_Rad_lbdv ` is the total anisotropic stress on the radial manifold, right? I would have just been expecting for something like `Anis_Cell_Stress_pts_Rad_lbdv ` and `Anis_Tissue_Stress_pts_Rad_lbdv ` to be calculated.

Come to think of it - the tissue stresses are calculated with the default `LBDV_Fit` object, as are the curvatures on the radial manifold - so for the tissue stresses it shouldn't make any difference whether the radial manifold is used or not, right?
```python
# ellipsoid mean curvature, and deviation from surface mean curvature:
self.H_ellps_lbdv_pts = Mean_Curvs_on_Ellipsoid(a0, a1, a2, LBDV_Fit.theta_pts, LBDV_Fit.phi_pts)
```

Still, wouldn't the cell-scale stresses on the radial manifold have to be calculated like this?
```python
self.Anis_Cell_Stress_Rad_pts_lbdv = self.TwoGammaVal * (Mean_Curv_Rad_lbdv_pts  - self.H_ellps_lbdv_pts)
```

**Comment by GrossBJ** [comment]
Yep, I think so. At the end of the day the calculations of the curvatures from the manifolds were very similar. The key point is that the lebedev quadrature points are located a different points on the surface for different parameterizations. And that's mostly the crux in being able to do calculations.  Since to add or subtract the values from previously calculated quantities they need to be at the same points. 

Enviado desde Yahoo Mail para Android 
 
  El mar, 8 de nov. de 2022 a la(s) 9:21, Johannes ***@***.***> escribió:   


Hi @GrossBJ ,


No worries I'm always happy to hear from you!


Thanks!


Are you implementing a version of this yourself?


Nah, I'm just copy-pasting code from the stress repository to separate functions here so that the whole becomes a bit easier to maintain. I'm not trying to reinvent the wheel :)

As for the radial manifold, I think it's alright for the total stress as you write but I'm not sure for the tissue stresses and the cell-scale stresses. The stresses on the radial manifold are calculated here (copying more code here to get the context):
# Use Gauss-Bonnet to test our resolution of the Radial manifold:
Rad_K_lbdv_pts = euc_kf.Combine_Chart_Quad_Vals(Manny_Rad.K_A_pts, Manny_Rad.K_B_pts, LBDV_VOL)
Gauss_Bonnet_Err_Rad = euc_kf.Integral_on_Manny(Rad_K_lbdv_pts, Manny_Rad, LBDV_VOL) - 4*np.pi
self.Gauss_Bonnet_Rel_Err_Rad = abs(Gauss_Bonnet_Err_Rad)/(4*np.pi)

Mean_Curv_Rad_lbdv_pts_unsigned = euc_kf.Combine_Chart_Quad_Vals(Manny_Rad.H_A_pts, Manny_Rad.H_B_pts, LBDV_VOL)

We estimate H0 on Radial Manifold: Integratal of H_Rad (on surface) divided by Rad surface area:
Ones_pts = 1.*(np.ones_like(Mean_Curv_Rad_lbdv_pts_unsigned))
H0_Rad_Int_of_H_over_Area = euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts_unsigned, Manny_Rad, LBDV_VOL) / euc_kf.Integral_on_Manny(Ones_pts, Manny_Rad, LBDV_VOL)

abs_H0_Rad_Int_of_H_over_Area = abs(H0_Rad_Int_of_H_over_Area) # should be positive
Mean_Curv_Rad_lbdv_pts = Mean_Curv_Rad_lbdv_pts_unsigned*abs_H0_Rad_Int_of_H_over_Area/H0_Rad_Int_of_H_over_Area # flip sign, if needed		
self.Anis_Stress_pts_Rad_lbdv = self.TwoGammaVal*(Mean_Curv_Rad_lbdv_pts - abs_H0_Rad_Int_of_H_over_Area)
		
Error in H approx between manifolds:
self.Mean_Curv_diff_Mannys = 0.5*( euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts - self.Mean_Curv_lbdv_pts, Manny_Rad, LBDV_VOL) + euc_kf.Integral_on_Manny(Mean_Curv_Rad_lbdv_pts - self.Mean_Curv_lbdv_pts, Manny, LBDV_Fit) )
where self.Anis_Stress_pts_Rad_lbdv  is the total anisotropic stress on the radial manifold, right? I would have just been expecting for something like Anis_Cell_Stress_pts_Rad_lbdv  and Anis_Tissue_Stress_pts_Rad_lbdv  to be calculated.

Come to think of it - the tissue stresses are calculated with the default LBDV_Fit object, as are the curvatures on the radial manifold - so for the tissue stresses it shouldn't make any difference whether the radial manifold is used or not, right?
# ellipsoid mean curvature, and deviation from surface mean curvature:
self.H_ellps_lbdv_pts = Mean_Curvs_on_Ellipsoid(a0, a1, a2, LBDV_Fit.theta_pts, LBDV_Fit.phi_pts)
Still, wouldn't the cell-scale stresses on the radial manifold have to be calculated like this?
self.Anis_Cell_Stress_Rad_pts_lbdv = self.TwoGammaVal * (Mean_Curv_Rad_lbdv_pts  - self.H_ellps_lbdv_pts)

**Comment by jo-mueller** [comment]
Original code has been implemented a few versions back.
